from dataclasses import dataclass
from enum import IntEnum, auto


class DataType(IntEnum):
    UNKNOWN = 0
    DEFAULT = auto()
    BOOL = auto()
    INT = auto()
    FLOAT = auto()
    RGBA = auto()
    VEC3 = auto()
    GEOMETRY = auto()
    STRING = auto()
    SHADER = auto()
    OBJECT = auto(),
    IMAGE = auto(),
    COLLECTION = auto(),
    TEXTURE = auto(),
    MATERIAL = auto()


@dataclass
class BuiltinNode:
    # The name used by blender, e.g. 'ShaderNodeMapRange'
    bl_name: str
    # The input sockets, name and data type
    inputs: list[tuple[str, DataType]] = []
    # The output sockets, name and data type
    outputs: list[tuple[str, DataType]] = []
    # A list of the properties that can be set on the node along with their possible values.
    props: list[tuple[str, list[str]]] = []


nodes = {
    'Particle Info': BuiltinNode('ShaderNodeParticleInfo',
                                 [],
                                 [('index', DataType.FLOAT), ('random', DataType.FLOAT), ('age', DataType.FLOAT), ('lifetime', DataType.FLOAT), (
                                     'location', DataType.VEC3), ('size', DataType.FLOAT), ('velocity', DataType.VEC3), ('angular_velocity', DataType.VEC3)],
                                 []),
    'Texture Coordinate': BuiltinNode('ShaderNodeTexCoord',
                                      [],
                                      [('generated', DataType.VEC3), ('normal', DataType.VEC3), ('uv', DataType.VEC3), ('object', DataType.VEC3), (
                                          'camera', DataType.VEC3), ('window', DataType.VEC3), ('reflection', DataType.VEC3)],
                                      []),
    'Tangent': BuiltinNode('ShaderNodeTangent',
                           [],
                           [('tangent', DataType.VEC3)],
                           [('direction_type', ['RADIAL', 'UV_MAP']), ('axis', ['X', 'Y', 'Z'])]),
    'Math': BuiltinNode('ShaderNodeMath',
                        [('value', DataType.FLOAT), ('value',
                                                     DataType.FLOAT), ('value', DataType.FLOAT)],
                        [('value', DataType.FLOAT)],
                        [('operation', ['ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'MULTIPLY_ADD', 'POWER', 'LOGARITHM', 'SQRT', 'INVERSE_SQRT', 'ABSOLUTE', 'EXPONENT', 'MINIMUM', 'MAXIMUM', 'LESS_THAN', 'GREATER_THAN', 'SIGN', 'COMPARE', 'SMOOTH_MIN', 'SMOOTH_MAX', 'ROUND', 'FLOOR', 'CEIL', 'TRUNC', 'FRACT', 'MODULO', 'WRAP', 'SNAP', 'PINGPONG', 'SINE', 'COSINE', 'TANGENT', 'ARCSINE', 'ARCCOSINE', 'ARCTANGENT', 'ARCTAN2', 'SINH', 'COSH', 'TANH', 'RADIANS', 'DEGREES'])]),
    'Vector Rotate': BuiltinNode('ShaderNodeVectorRotate',
                                 [('vector', DataType.VEC3), ('center', DataType.VEC3), ('axis', DataType.VEC3), (
                                     'angle', DataType.FLOAT), ('rotation', DataType.VEC3)],
                                 [('vector', DataType.VEC3)],
                                 [('rotation_type', ['AXIS_ANGLE', 'X_AXIS', 'Y_AXIS', 'Z_AXIS', 'EULER_XYZ'])]),
    'Combine XYZ': BuiltinNode('ShaderNodeCombineXYZ',
                               [('x', DataType.FLOAT), ('y', DataType.FLOAT),
                                ('z', DataType.FLOAT)],
                               [('vector', DataType.VEC3)],
                               []),
    'Ambient Occlusion': BuiltinNode('ShaderNodeAmbientOcclusion',
                                     [('color', DataType.RGBA), ('distance',
                                                                 DataType.FLOAT), ('normal', DataType.VEC3)],
                                     [('color', DataType.RGBA),
                                      ('ao', DataType.FLOAT)],
                                     []),
    'Blackbody': BuiltinNode('ShaderNodeBlackbody',
                             [('temperature', DataType.FLOAT)],
                             [('color', DataType.RGBA)],
                             []),
    'White Noise Texture': BuiltinNode('ShaderNodeTexWhiteNoise',
                                       [('vector', DataType.VEC3),
                                        ('w', DataType.FLOAT)],
                                       [('value', DataType.FLOAT),
                                        ('color', DataType.RGBA)],
                                       [('noise_dimensions', ['1D', '2D', '3D', '4D'])]),
    'Clamp': BuiltinNode('ShaderNodeClamp',
                         [('value', DataType.FLOAT),
                          ('min', DataType.FLOAT), ('max', DataType.FLOAT)],
                         [('result', DataType.FLOAT)],
                         [('clamp_type', ['MINMAX', 'RANGE'])]),
    'Wavelength': BuiltinNode('ShaderNodeWavelength',
                              [('wavelength', DataType.FLOAT)],
                              [('color', DataType.RGBA)],
                              []),
    'Principled Hair BSDF': BuiltinNode('ShaderNodeBsdfHairPrincipled',
                                        [('color', DataType.RGBA), ('melanin', DataType.FLOAT), ('melanin_redness', DataType.FLOAT), ('tint', DataType.RGBA), ('absorption_coefficient', DataType.VEC3), ('roughness', DataType.FLOAT), (
                                            'radial_roughness', DataType.FLOAT), ('coat', DataType.FLOAT), ('ior', DataType.FLOAT), ('offset', DataType.FLOAT), ('random_color', DataType.FLOAT), ('random_roughness', DataType.FLOAT), ('random', DataType.FLOAT)],
                                        [('bsdf', DataType.SHADER)],
                                        [('parametrization', ['ABSORPTION', 'MELANIN', 'COLOR'])]),
    'Separate RGB': BuiltinNode('ShaderNodeSeparateRGB',
                                [('image', DataType.RGBA)],
                                [('r', DataType.FLOAT), ('g', DataType.FLOAT),
                                 ('b', DataType.FLOAT)],
                                []),
    'Hair Info': BuiltinNode('ShaderNodeHairInfo',
                             [],
                             [('is_strand', DataType.FLOAT), ('intercept', DataType.FLOAT), ('length', DataType.FLOAT), (
                                 'thickness', DataType.FLOAT), ('tangent_normal', DataType.VEC3), ('random', DataType.FLOAT)],
                             []),
    'Displacement': BuiltinNode('ShaderNodeDisplacement',
                                [('height', DataType.FLOAT), ('midlevel', DataType.FLOAT),
                                 ('scale', DataType.FLOAT), ('normal', DataType.VEC3)],
                                [('displacement', DataType.VEC3)],
                                [('space', ['OBJECT', 'WORLD'])]),
    'Environment Texture': BuiltinNode('ShaderNodeTexEnvironment',
                                       [('vector', DataType.VEC3)],
                                       [('color', DataType.RGBA)],
                                       [('projection', ['EQUIRECTANGULAR', 'MIRROR_BALL']), ('interpolation', ['Linear', 'Closest', 'Cubic', 'Smart'])]),
    'Point Density': BuiltinNode('ShaderNodeTexPointDensity',
                                 [('vector', DataType.VEC3)],
                                 [('color', DataType.RGBA),
                                  ('density', DataType.FLOAT)],
                                 [('point_source', ['PARTICLE_SYSTEM', 'OBJECT']), ('space', ['OBJECT', 'WORLD']), ('interpolation', ['Closest', 'Linear', 'Cubic']), ('particle_color_source', ['PARTICLE_AGE', 'PARTICLE_SPEED', 'PARTICLE_VELOCITY']), ('vertex_color_source', ['VERTEX_COLOR', 'VERTEX_WEIGHT', 'VERTEX_NORMAL'])]),
    'Wireframe': BuiltinNode('ShaderNodeWireframe',
                             [('size', DataType.FLOAT)],
                             [('fac', DataType.FLOAT)],
                             []),
    'Checker Texture': BuiltinNode('ShaderNodeTexChecker',
                                   [('vector', DataType.VEC3), ('color1', DataType.RGBA),
                                    ('color2', DataType.RGBA), ('scale', DataType.FLOAT)],
                                   [('color', DataType.RGBA),
                                    ('fac', DataType.FLOAT)],
                                   []),
    'IES Texture': BuiltinNode('ShaderNodeTexIES',
                               [('vector', DataType.VEC3),
                                ('strength', DataType.FLOAT)],
                               [('fac', DataType.FLOAT)],
                               [('mode', ['INTERNAL', 'EXTERNAL'])]),
    'Mix': BuiltinNode('ShaderNodeMixRGB',
                       [('fac', DataType.FLOAT), ('color1', DataType.RGBA),
                        ('color2', DataType.RGBA)],
                       [('color', DataType.RGBA)],
                       [('blend_type', ['MIX', 'DARKEN', 'MULTIPLY', 'BURN', 'LIGHTEN', 'SCREEN', 'DODGE', 'ADD', 'OVERLAY', 'SOFT_LIGHT', 'LINEAR_LIGHT', 'DIFFERENCE', 'SUBTRACT', 'DIVIDE', 'HUE', 'SATURATION', 'COLOR', 'VALUE'])]),
    'Geometry': BuiltinNode('ShaderNodeNewGeometry',
                            [],
                            [('position', DataType.VEC3), ('normal', DataType.VEC3), ('tangent', DataType.VEC3), ('true_normal', DataType.VEC3), ('incoming', DataType.VEC3), (
                                'parametric', DataType.VEC3), ('backfacing', DataType.FLOAT), ('pointiness', DataType.FLOAT), ('random_per_island', DataType.FLOAT)],
                            []),
    'Magic Texture': BuiltinNode('ShaderNodeTexMagic',
                                 [('vector', DataType.VEC3), ('scale',
                                                              DataType.FLOAT), ('distortion', DataType.FLOAT)],
                                 [('color', DataType.RGBA),
                                  ('fac', DataType.FLOAT)],
                                 []),
    'RGB Curves': BuiltinNode('ShaderNodeRGBCurve',
                              [('fac', DataType.FLOAT), ('color', DataType.RGBA)],
                              [('color', DataType.RGBA)],
                              []),
    'Principled Volume': BuiltinNode('ShaderNodeVolumePrincipled',
                                     [('color', DataType.RGBA), ('color_attribute', DataType.STRING), ('density', DataType.FLOAT), ('density_attribute', DataType.STRING), ('anisotropy', DataType.FLOAT), ('absorption_color', DataType.RGBA), (
                                         'emission_strength', DataType.FLOAT), ('emission_color', DataType.RGBA), ('blackbody_intensity', DataType.FLOAT), ('blackbody_tint', DataType.RGBA), ('temperature', DataType.FLOAT), ('temperature_attribute', DataType.STRING)],
                                     [('volume', DataType.SHADER)],
                                     []),
    'Object Info': BuiltinNode('ShaderNodeObjectInfo',
                               [],
                               [('location', DataType.VEC3), ('color', DataType.RGBA), ('alpha', DataType.FLOAT), (
                                   'object_index', DataType.FLOAT), ('material_index', DataType.FLOAT), ('random', DataType.FLOAT)],
                               []),
    'Sky Texture': BuiltinNode('ShaderNodeTexSky',
                               [('vector', DataType.VEC3)],
                               [('color', DataType.RGBA)],
                               [('sky_type', ['PREETHAM', 'HOSEK_WILKIE', 'NISHITA'])]),
    'Velvet BSDF': BuiltinNode('ShaderNodeBsdfVelvet',
                               [('color', DataType.RGBA), ('sigma',
                                                           DataType.FLOAT), ('normal', DataType.VEC3)],
                               [('bsdf', DataType.SHADER)],
                               []),
    'Musgrave Texture': BuiltinNode('ShaderNodeTexMusgrave',
                                    [('vector', DataType.VEC3), ('w', DataType.FLOAT), ('scale', DataType.FLOAT), ('detail', DataType.FLOAT), (
                                        'dimension', DataType.FLOAT), ('lacunarity', DataType.FLOAT), ('offset', DataType.FLOAT), ('gain', DataType.FLOAT)],
                                    [('fac', DataType.FLOAT)],
                                    [('musgrave_dimensions', ['1D', '2D', '3D', '4D']), ('musgrave_type', ['MULTIFRACTAL', 'RIDGED_MULTIFRACTAL', 'HYBRID_MULTIFRACTAL', 'FBM', 'HETERO_TERRAIN'])]),
    'Bright/Contrast': BuiltinNode('ShaderNodeBrightContrast',
                                   [('color', DataType.RGBA), ('bright',
                                                               DataType.FLOAT), ('contrast', DataType.FLOAT)],
                                   [('color', DataType.RGBA)],
                                   []),
    'Volume Scatter': BuiltinNode('ShaderNodeVolumeScatter',
                                  [('color', DataType.RGBA), ('density',
                                                              DataType.FLOAT), ('anisotropy', DataType.FLOAT)],
                                  [('volume', DataType.SHADER)],
                                  []),
    'Separate XYZ': BuiltinNode('ShaderNodeSeparateXYZ',
                                [('vector', DataType.VEC3)],
                                [('x', DataType.FLOAT), ('y', DataType.FLOAT),
                                 ('z', DataType.FLOAT)],
                                []),
    'Holdout': BuiltinNode('ShaderNodeHoldout',
                           [],
                           [('holdout', DataType.SHADER)],
                           []),
    'Refraction BSDF': BuiltinNode('ShaderNodeBsdfRefraction',
                                   [('color', DataType.RGBA), ('roughness', DataType.FLOAT),
                                    ('ior', DataType.FLOAT), ('normal', DataType.VEC3)],
                                   [('bsdf', DataType.SHADER)],
                                   [('distribution', ['SHARP', 'BECKMANN', 'GGX'])]),
    'Mapping': BuiltinNode('ShaderNodeMapping',
                           [('vector', DataType.VEC3), ('location', DataType.VEC3),
                            ('rotation', DataType.VEC3), ('scale', DataType.VEC3)],
                           [('vector', DataType.VEC3)],
                           [('vector_type', ['POINT', 'TEXTURE', 'VECTOR', 'NORMAL'])]),
    'Light Falloff': BuiltinNode('ShaderNodeLightFalloff',
                                 [('strength', DataType.FLOAT),
                                  ('smooth', DataType.FLOAT)],
                                 [('quadratic', DataType.FLOAT), ('linear',
                                                                  DataType.FLOAT), ('constant', DataType.FLOAT)],
                                 []),
    'Attribute': BuiltinNode('ShaderNodeAttribute',
                             [],
                             [('color', DataType.RGBA), ('vector', DataType.VEC3),
                              ('fac', DataType.FLOAT), ('alpha', DataType.FLOAT)],
                             [('attribute_type', ['GEOMETRY', 'OBJECT', 'INSTANCER'])]),
    'Normal Map': BuiltinNode('ShaderNodeNormalMap',
                              [('strength', DataType.FLOAT),
                               ('color', DataType.RGBA)],
                              [('normal', DataType.VEC3)],
                              [('space', ['TANGENT', 'OBJECT', 'WORLD', 'BLENDER_OBJECT', 'BLENDER_WORLD'])]),
    'Hair BSDF': BuiltinNode('ShaderNodeBsdfHair',
                             [('color', DataType.RGBA), ('offset', DataType.FLOAT), ('roughnessu',
                                                                                     DataType.FLOAT), ('roughnessv', DataType.FLOAT), ('tangent', DataType.VEC3)],
                             [('bsdf', DataType.SHADER)],
                             [('component', ['Reflection', 'Transmission'])]),
    'Specular BSDF': BuiltinNode('ShaderNodeEeveeSpecular',
                                 [('base_color', DataType.RGBA), ('specular', DataType.RGBA), ('roughness', DataType.FLOAT), ('emissive_color', DataType.RGBA), ('transparency', DataType.FLOAT), (
                                     'normal', DataType.VEC3), ('clear_coat', DataType.FLOAT), ('clear_coat_roughness', DataType.FLOAT), ('clear_coat_normal', DataType.VEC3), ('ambient_occlusion', DataType.FLOAT)],
                                 [('bsdf', DataType.SHADER)],
                                 []),
    'Emission': BuiltinNode('ShaderNodeEmission',
                            [('color', DataType.RGBA),
                             ('strength', DataType.FLOAT)],
                            [('emission', DataType.SHADER)],
                            []),
    'Line Style Output': BuiltinNode('ShaderNodeOutputLineStyle',
                                     [('color', DataType.RGBA), ('color_fac', DataType.FLOAT),
                                      ('alpha', DataType.FLOAT), ('alpha_fac', DataType.FLOAT)],
                                     [],
                                     [('target', ['ALL', 'EEVEE', 'CYCLES']), ('blend_type', ['MIX', 'DARKEN', 'MULTIPLY', 'BURN', 'LIGHTEN', 'SCREEN', 'DODGE', 'ADD', 'OVERLAY', 'SOFT_LIGHT', 'LINEAR_LIGHT', 'DIFFERENCE', 'SUBTRACT', 'DIVIDE', 'HUE', 'SATURATION', 'COLOR', 'VALUE'])]),
    'Combine RGB': BuiltinNode('ShaderNodeCombineRGB',
                               [('r', DataType.FLOAT), ('g', DataType.FLOAT),
                                ('b', DataType.FLOAT)],
                               [('image', DataType.RGBA)],
                               []),
    'Mix Shader': BuiltinNode('ShaderNodeMixShader',
                              [('fac', DataType.FLOAT), ('shader',
                                                         DataType.SHADER), ('shader', DataType.SHADER)],
                              [('shader', DataType.SHADER)],
                              []),
    'Map Range': BuiltinNode('ShaderNodeMapRange',
                             [('value', DataType.FLOAT), ('from_min', DataType.FLOAT), ('from_max', DataType.FLOAT), ('to_min', DataType.FLOAT), ('to_max', DataType.FLOAT), ('steps', DataType.FLOAT), (
                                 'vector', DataType.VEC3), ('from_min', DataType.VEC3), ('from_max', DataType.VEC3), ('to_min', DataType.VEC3), ('to_max', DataType.VEC3), ('steps', DataType.VEC3)],
                             [('result', DataType.FLOAT),
                              ('vector', DataType.VEC3)],
                             [('interpolation_type', ['LINEAR', 'STEPPED', 'SMOOTHSTEP', 'SMOOTHERSTEP']), ('data_type', ['FLOAT', 'FLOAT_VECTOR'])]),
    'Value': BuiltinNode('ShaderNodeValue',
                         [],
                         [('value', DataType.FLOAT)],
                         []),
    'Wave Texture': BuiltinNode('ShaderNodeTexWave',
                                [('vector', DataType.VEC3), ('scale', DataType.FLOAT), ('distortion', DataType.FLOAT), ('detail', DataType.FLOAT), (
                                    'detail_scale', DataType.FLOAT), ('detail_roughness', DataType.FLOAT), ('phase_offset', DataType.FLOAT)],
                                [('color', DataType.RGBA),
                                 ('fac', DataType.FLOAT)],
                                [('wave_type', ['BANDS', 'RINGS']), ('bands_direction', ['X', 'Y', 'Z', 'DIAGONAL']), ('rings_direction', ['X', 'Y', 'Z', 'SPHERICAL']), ('wave_profile', ['SIN', 'SAW', 'TRI'])]),
    'Material Output': BuiltinNode('ShaderNodeOutputMaterial',
                                   [('surface', DataType.SHADER), ('volume',
                                                                   DataType.SHADER), ('displacement', DataType.VEC3)],
                                   [],
                                   [('target', ['ALL', 'EEVEE', 'CYCLES'])]),
    'Gamma': BuiltinNode('ShaderNodeGamma',
                         [('color', DataType.RGBA), ('gamma', DataType.FLOAT)],
                         [('color', DataType.RGBA)],
                         []),
    'Volume Info': BuiltinNode('ShaderNodeVolumeInfo',
                               [],
                               [('color', DataType.RGBA), ('density', DataType.FLOAT),
                                ('flame', DataType.FLOAT), ('temperature', DataType.FLOAT)],
                               []),
    'Subsurface Scattering': BuiltinNode('ShaderNodeSubsurfaceScattering',
                                         [('color', DataType.RGBA), ('scale', DataType.FLOAT), ('radius', DataType.VEC3), (
                                             'ior', DataType.FLOAT), ('anisotropy', DataType.FLOAT), ('normal', DataType.VEC3)],
                                         [('bssrdf', DataType.SHADER)],
                                         [('falloff', ['BURLEY', 'RANDOM_WALK_FIXED_RADIUS', 'RANDOM_WALK'])]),
    'Vertex Color': BuiltinNode('ShaderNodeVertexColor',
                                [],
                                [('color', DataType.RGBA),
                                 ('alpha', DataType.FLOAT)],
                                []),
    'Noise Texture': BuiltinNode('ShaderNodeTexNoise',
                                 [('vector', DataType.VEC3), ('w', DataType.FLOAT), ('scale', DataType.FLOAT), (
                                     'detail', DataType.FLOAT), ('roughness', DataType.FLOAT), ('distortion', DataType.FLOAT)],
                                 [('fac', DataType.FLOAT),
                                  ('color', DataType.RGBA)],
                                 [('noise_dimensions', ['1D', '2D', '3D', '4D'])]),
    'Combine HSV': BuiltinNode('ShaderNodeCombineHSV',
                               [('h', DataType.FLOAT), ('s', DataType.FLOAT),
                                ('v', DataType.FLOAT)],
                               [('color', DataType.RGBA)],
                               []),
    'Script': BuiltinNode('ShaderNodeScript',
                          [],
                          [],
                          [('mode', ['INTERNAL', 'EXTERNAL'])]),
    'Normal': BuiltinNode('ShaderNodeNormal',
                          [('normal', DataType.VEC3)],
                          [('normal', DataType.VEC3), ('dot', DataType.FLOAT)],
                          []),
    'Glossy BSDF': BuiltinNode('ShaderNodeBsdfGlossy',
                               [('color', DataType.RGBA), ('roughness',
                                                           DataType.FLOAT), ('normal', DataType.VEC3)],
                               [('bsdf', DataType.SHADER)],
                               [('distribution', ['SHARP', 'BECKMANN', 'GGX', 'ASHIKHMIN_SHIRLEY', 'MULTI_GGX'])]),
    'Camera Data': BuiltinNode('ShaderNodeCameraData',
                               [],
                               [('view_vector', DataType.VEC3), ('view_z_depth',
                                                                 DataType.FLOAT), ('view_distance', DataType.FLOAT)],
                               []),
    'UV Along Stroke': BuiltinNode('ShaderNodeUVAlongStroke',
                                   [],
                                   [('uv', DataType.VEC3)],
                                   []),
    'Layer Weight': BuiltinNode('ShaderNodeLayerWeight',
                                [('blend', DataType.FLOAT),
                                 ('normal', DataType.VEC3)],
                                [('fresnel', DataType.FLOAT),
                                 ('facing', DataType.FLOAT)],
                                []),
    'Vector Displacement': BuiltinNode('ShaderNodeVectorDisplacement',
                                       [('vector', DataType.RGBA), ('midlevel',
                                                                    DataType.FLOAT), ('scale', DataType.FLOAT)],
                                       [('displacement', DataType.VEC3)],
                                       [('space', ['TANGENT', 'OBJECT', 'WORLD'])]),
    'World Output': BuiltinNode('ShaderNodeOutputWorld',
                                [('surface', DataType.SHADER),
                                 ('volume', DataType.SHADER)],
                                [],
                                [('target', ['ALL', 'EEVEE', 'CYCLES'])]),
    'Diffuse BSDF': BuiltinNode('ShaderNodeBsdfDiffuse',
                                [('color', DataType.RGBA), ('roughness',
                                                            DataType.FLOAT), ('normal', DataType.VEC3)],
                                [('bsdf', DataType.SHADER)],
                                []),
    'Float Curve': BuiltinNode('ShaderNodeFloatCurve',
                               [('factor', DataType.FLOAT),
                                ('value', DataType.FLOAT)],
                               [('value', DataType.FLOAT)],
                               []),
    'Point Info': BuiltinNode('ShaderNodePointInfo',
                              [],
                              [('position', DataType.VEC3), ('radius',
                                                             DataType.FLOAT), ('random', DataType.FLOAT)],
                              []),
    'Vector Transform': BuiltinNode('ShaderNodeVectorTransform',
                                    [('vector', DataType.VEC3)],
                                    [('vector', DataType.VEC3)],
                                    [('vector_type', ['POINT', 'VECTOR', 'NORMAL']), ('convert_from', ['WORLD', 'OBJECT', 'CAMERA']), ('convert_to', ['WORLD', 'OBJECT', 'CAMERA'])]),
    'Bevel': BuiltinNode('ShaderNodeBevel',
                         [('radius', DataType.FLOAT), ('normal', DataType.VEC3)],
                         [('normal', DataType.VEC3)],
                         []),
    'Light Output': BuiltinNode('ShaderNodeOutputLight',
                                [('surface', DataType.SHADER)],
                                [],
                                [('target', ['ALL', 'EEVEE', 'CYCLES'])]),
    'Volume Absorption': BuiltinNode('ShaderNodeVolumeAbsorption',
                                     [('color', DataType.RGBA),
                                      ('density', DataType.FLOAT)],
                                     [('volume', DataType.SHADER)],
                                     []),
    'Hue Saturation Value': BuiltinNode('ShaderNodeHueSaturation',
                                        [('hue', DataType.FLOAT), ('saturation', DataType.FLOAT), (
                                            'value', DataType.FLOAT), ('fac', DataType.FLOAT), ('color', DataType.RGBA)],
                                        [('color', DataType.RGBA)],
                                        []),
    'Bump': BuiltinNode('ShaderNodeBump',
                        [('strength', DataType.FLOAT), ('distance', DataType.FLOAT), ('height', DataType.FLOAT), (
                            'height_dx', DataType.FLOAT), ('height_dy', DataType.FLOAT), ('normal', DataType.VEC3)],
                        [('normal', DataType.VEC3)],
                        []),
    'Transparent BSDF': BuiltinNode('ShaderNodeBsdfTransparent',
                                    [('color', DataType.RGBA)],
                                    [('bsdf', DataType.SHADER)],
                                    []),
    'Shader to RGB': BuiltinNode('ShaderNodeShaderToRGB',
                                 [('shader', DataType.SHADER)],
                                 [('color', DataType.RGBA),
                                  ('alpha', DataType.FLOAT)],
                                 []),
    'Principled BSDF': BuiltinNode('ShaderNodeBsdfPrincipled',
                                   [('base_color', DataType.RGBA), ('subsurface', DataType.FLOAT), ('subsurface_radius', DataType.VEC3), ('subsurface_color', DataType.RGBA), ('subsurface_ior', DataType.FLOAT), ('subsurface_anisotropy', DataType.FLOAT), ('metallic', DataType.FLOAT), ('specular', DataType.FLOAT), ('specular_tint', DataType.FLOAT), ('roughness', DataType.FLOAT), ('anisotropic', DataType.FLOAT), ('anisotropic_rotation', DataType.FLOAT), (
                                       'sheen', DataType.FLOAT), ('sheen_tint', DataType.FLOAT), ('clearcoat', DataType.FLOAT), ('clearcoat_roughness', DataType.FLOAT), ('ior', DataType.FLOAT), ('transmission', DataType.FLOAT), ('transmission_roughness', DataType.FLOAT), ('emission', DataType.RGBA), ('emission_strength', DataType.FLOAT), ('alpha', DataType.FLOAT), ('normal', DataType.VEC3), ('clearcoat_normal', DataType.VEC3), ('tangent', DataType.VEC3)],
                                   [('bsdf', DataType.SHADER)],
                                   [('distribution', ['GGX', 'MULTI_GGX']), ('subsurface_method', ['BURLEY', 'RANDOM_WALK_FIXED_RADIUS', 'RANDOM_WALK'])]),
    'Fresnel': BuiltinNode('ShaderNodeFresnel',
                           [('ior', DataType.FLOAT), ('normal', DataType.VEC3)],
                           [('fac', DataType.FLOAT)],
                           []),
    'Toon BSDF': BuiltinNode('ShaderNodeBsdfToon',
                             [('color', DataType.RGBA), ('size', DataType.FLOAT),
                              ('smooth', DataType.FLOAT), ('normal', DataType.VEC3)],
                             [('bsdf', DataType.SHADER)],
                             [('component', ['DIFFUSE', 'GLOSSY'])]),
    'Background': BuiltinNode('ShaderNodeBackground',
                              [('color', DataType.RGBA),
                               ('strength', DataType.FLOAT)],
                              [('background', DataType.SHADER)],
                              []),
    'RGB': BuiltinNode('ShaderNodeRGB',
                       [],
                       [('color', DataType.RGBA)],
                       []),
    '': BuiltinNode('ShaderNodeOutputAOV',
                    [('color', DataType.RGBA), ('value', DataType.FLOAT)],
                    [],
                    []),
    'Brick Texture': BuiltinNode('ShaderNodeTexBrick',
                                 [('vector', DataType.VEC3), ('color1', DataType.RGBA), ('color2', DataType.RGBA), ('mortar', DataType.RGBA), ('scale', DataType.FLOAT), (
                                     'mortar_size', DataType.FLOAT), ('mortar_smooth', DataType.FLOAT), ('bias', DataType.FLOAT), ('brick_width', DataType.FLOAT), ('row_height', DataType.FLOAT)],
                                 [('color', DataType.RGBA),
                                  ('fac', DataType.FLOAT)],
                                 []),
    'Vector Math': BuiltinNode('ShaderNodeVectorMath',
                               [('vector', DataType.VEC3), ('vector', DataType.VEC3),
                                ('vector', DataType.VEC3), ('scale', DataType.FLOAT)],
                               [('vector', DataType.VEC3),
                                ('value', DataType.FLOAT)],
                               [('operation', ['ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'MULTIPLY_ADD', 'CROSS_PRODUCT', 'PROJECT', 'REFLECT', 'REFRACT', 'FACEFORWARD', 'DOT_PRODUCT', 'DISTANCE', 'LENGTH', 'SCALE', 'NORMALIZE', 'ABSOLUTE', 'MINIMUM', 'MAXIMUM', 'FLOOR', 'CEIL', 'FRACTION', 'MODULO', 'WRAP', 'SNAP', 'SINE', 'COSINE', 'TANGENT'])]),
    'Voronoi Texture': BuiltinNode('ShaderNodeTexVoronoi',
                                   [('vector', DataType.VEC3), ('w', DataType.FLOAT), ('scale', DataType.FLOAT), (
                                       'smoothness', DataType.FLOAT), ('exponent', DataType.FLOAT), ('randomness', DataType.FLOAT)],
                                   [('distance', DataType.FLOAT), ('color', DataType.RGBA), (
                                       'position', DataType.VEC3), ('w', DataType.FLOAT), ('radius', DataType.FLOAT)],
                                   [('voronoi_dimensions', ['1D', '2D', '3D', '4D']), ('distance', ['EUCLIDEAN', 'MANHATTAN', 'CHEBYCHEV', 'MINKOWSKI']), ('feature', ['F1', 'F2', 'SMOOTH_F1', 'DISTANCE_TO_EDGE', 'N_SPHERE_RADIUS'])]),
    'Translucent BSDF': BuiltinNode('ShaderNodeBsdfTranslucent',
                                    [('color', DataType.RGBA),
                                     ('normal', DataType.VEC3)],
                                    [('bsdf', DataType.SHADER)],
                                    []),
    'Add Shader': BuiltinNode('ShaderNodeAddShader',
                              [('shader', DataType.SHADER),
                               ('shader', DataType.SHADER)],
                              [('shader', DataType.SHADER)],
                              []),
    'Glass BSDF': BuiltinNode('ShaderNodeBsdfGlass',
                              [('color', DataType.RGBA), ('roughness', DataType.FLOAT),
                               ('ior', DataType.FLOAT), ('normal', DataType.VEC3)],
                              [('bsdf', DataType.SHADER)],
                              [('distribution', ['SHARP', 'BECKMANN', 'GGX', 'MULTI_GGX'])]),
    'ColorRamp': BuiltinNode('ShaderNodeValToRGB',
                             [('fac', DataType.FLOAT)],
                             [('color', DataType.RGBA),
                              ('alpha', DataType.FLOAT)],
                             []),
    'Separate HSV': BuiltinNode('ShaderNodeSeparateHSV',
                                [('color', DataType.RGBA)],
                                [('h', DataType.FLOAT), ('s', DataType.FLOAT),
                                 ('v', DataType.FLOAT)],
                                []),
    'UV Map': BuiltinNode('ShaderNodeUVMap',
                          [],
                          [('uv', DataType.VEC3)],
                          []),
    'Image Texture': BuiltinNode('ShaderNodeTexImage',
                                 [('vector', DataType.VEC3)],
                                 [('color', DataType.RGBA),
                                  ('alpha', DataType.FLOAT)],
                                 [('projection', ['FLAT', 'BOX', 'SPHERE', 'TUBE']), ('interpolation', ['Linear', 'Closest', 'Cubic', 'Smart']), ('extension', ['REPEAT', 'EXTEND', 'CLIP'])]),
    'Light Path': BuiltinNode('ShaderNodeLightPath',
                              [],
                              [('is_camera_ray', DataType.FLOAT), ('is_shadow_ray', DataType.FLOAT), ('is_diffuse_ray', DataType.FLOAT), ('is_glossy_ray', DataType.FLOAT), ('is_singular_ray', DataType.FLOAT), ('is_reflection_ray', DataType.FLOAT), ('is_transmission_ray',
                                                                                                                                                                                                                                                         DataType.FLOAT), ('ray_length', DataType.FLOAT), ('ray_depth', DataType.FLOAT), ('diffuse_depth', DataType.FLOAT), ('glossy_depth', DataType.FLOAT), ('transparent_depth', DataType.FLOAT), ('transmission_depth', DataType.FLOAT)],
                              []),
    'Invert': BuiltinNode('ShaderNodeInvert',
                          [('fac', DataType.FLOAT), ('color', DataType.RGBA)],
                          [('color', DataType.RGBA)],
                          []),
    'Anisotropic BSDF': BuiltinNode('ShaderNodeBsdfAnisotropic',
                                    [('color', DataType.RGBA), ('roughness', DataType.FLOAT), ('anisotropy', DataType.FLOAT), (
                                        'rotation', DataType.FLOAT), ('normal', DataType.VEC3), ('tangent', DataType.VEC3)],
                                    [('bsdf', DataType.SHADER)],
                                    [('distribution', ['BECKMANN', 'GGX', 'MULTI_GGX', 'ASHIKHMIN_SHIRLEY'])]),
    'Vector Curves': BuiltinNode('ShaderNodeVectorCurve',
                                 [('fac', DataType.FLOAT),
                                  ('vector', DataType.VEC3)],
                                 [('vector', DataType.VEC3)],
                                 []),
    'RGB to BW': BuiltinNode('ShaderNodeRGBToBW',
                             [('color', DataType.RGBA)],
                             [('val', DataType.FLOAT)],
                             []),
    'Gradient Texture': BuiltinNode('ShaderNodeTexGradient',
                                    [('vector', DataType.VEC3)],
                                    [('color', DataType.RGBA),
                                     ('fac', DataType.FLOAT)],
                                    [('gradient_type', ['LINEAR', 'QUADRATIC', 'EASING', 'DIAGONAL', 'SPHERICAL', 'QUADRATIC_SPHERE', 'RADIAL'])]),
    # GEOMETRYNODES ONLY!!!!
    'Curve Line': BuiltinNode('GeometryNodeCurvePrimitiveLine',
                              [('start', DataType.VEC3), ('end', DataType.VEC3),
                               ('direction', DataType.VEC3), ('length', DataType.FLOAT)],
                              [('curve', DataType.GEOMETRY)],
                              [('mode', ['POINTS', 'DIRECTION'])]),
    'Instances to Points': BuiltinNode('GeometryNodeInstancesToPoints',
                                       [('instances', DataType.GEOMETRY), ('selection', DataType.BOOL), (
                                           'position', DataType.VEC3), ('radius', DataType.FLOAT)],
                                       [('points', DataType.GEOMETRY)],
                                       []),
    'Rotate Euler': BuiltinNode('FunctionNodeRotateEuler',
                                [('rotation', DataType.VEC3), ('rotate_by', DataType.VEC3),
                                 ('axis', DataType.VEC3), ('angle', DataType.FLOAT)],
                                [('rotation', DataType.VEC3)],
                                [('type', ['AXIS_ANGLE', 'EULER']), ('space', ['OBJECT', 'LOCAL'])]),
    'Grid': BuiltinNode('GeometryNodeMeshGrid',
                        [('size_x', DataType.FLOAT), ('size_y', DataType.FLOAT),
                         ('vertices_x', DataType.INT), ('vertices_y', DataType.INT)],
                        [('mesh', DataType.GEOMETRY)],
                        []),
    'Rotate Instances': BuiltinNode('GeometryNodeRotateInstances',
                                    [('instances', DataType.GEOMETRY), ('selection', DataType.BOOL), ('rotation',
                                                                                                      DataType.VEC3), ('pivot_point', DataType.VEC3), ('local_space', DataType.BOOL)],
                                    [('instances', DataType.GEOMETRY)],
                                    []),
    'Arc': BuiltinNode('GeometryNodeCurveArc',
                       [('resolution', DataType.INT), ('start', DataType.VEC3), ('middle', DataType.VEC3), ('end', DataType.VEC3), ('radius', DataType.FLOAT), ('start_angle',
                                                                                                                                                                DataType.FLOAT), ('sweep_angle', DataType.FLOAT), ('offset_angle', DataType.FLOAT), ('connect_center', DataType.BOOL), ('invert_arc', DataType.BOOL)],
                       [('curve', DataType.GEOMETRY), ('center', DataType.VEC3),
                        ('normal', DataType.VEC3), ('radius', DataType.FLOAT)],
                       [('mode', ['POINTS', 'RADIUS'])]),
    'Curve Circle': BuiltinNode('GeometryNodeCurvePrimitiveCircle',
                                [('resolution', DataType.INT), ('point_1', DataType.VEC3), ('point_2',
                                                                                            DataType.VEC3), ('point_3', DataType.VEC3), ('radius', DataType.FLOAT)],
                                [('curve', DataType.GEOMETRY),
                                 ('center', DataType.VEC3)],
                                [('mode', ['POINTS', 'RADIUS'])]),
    'Volume to Mesh': BuiltinNode('GeometryNodeVolumeToMesh',
                                  [('volume', DataType.GEOMETRY), ('voxel_size', DataType.FLOAT), ('voxel_amount',
                                                                                                   DataType.FLOAT), ('threshold', DataType.FLOAT), ('adaptivity', DataType.FLOAT)],
                                  [('mesh', DataType.GEOMETRY)],
                                  [('resolution_mode', ['GRID', 'VOXEL_AMOUNT', 'VOXEL_SIZE'])]),
    'Boolean Math': BuiltinNode('FunctionNodeBooleanMath',
                                [('boolean', DataType.BOOL),
                                 ('boolean', DataType.BOOL)],
                                [('boolean', DataType.BOOL)],
                                [('operation', ['AND', 'OR', 'NOT', 'NAND', 'NOR', 'XNOR', 'XOR', 'IMPLY', 'NIMPLY'])]),
    'Slice String': BuiltinNode('FunctionNodeSliceString',
                                [('string', DataType.STRING), ('position',
                                                               DataType.INT), ('length', DataType.INT)],
                                [('string', DataType.STRING)],
                                []),
    'Cone': BuiltinNode('GeometryNodeMeshCone',
                        [('vertices', DataType.INT), ('side_segments', DataType.INT), ('fill_segments', DataType.INT),
                         ('radius_top', DataType.FLOAT), ('radius_bottom', DataType.FLOAT), ('depth', DataType.FLOAT)],
                        [('mesh', DataType.GEOMETRY), ('top', DataType.BOOL),
                         ('bottom', DataType.BOOL), ('side', DataType.BOOL)],
                        [('fill_type', ['NONE', 'NGON', 'TRIANGLE_FAN'])]),
    'Realize Instances': BuiltinNode('GeometryNodeRealizeInstances',
                                     [('geometry', DataType.GEOMETRY)],
                                     [('geometry', DataType.GEOMETRY)],
                                     []),
    'Remove Attribute': BuiltinNode('GeometryNodeRemoveAttribute',
                                    [('geometry', DataType.GEOMETRY),
                                     ('name', DataType.STRING)],
                                    [('geometry', DataType.GEOMETRY)],
                                    []),
    'UV Sphere': BuiltinNode('GeometryNodeMeshUVSphere',
                             [('segments', DataType.INT), ('rings',
                                                           DataType.INT), ('radius', DataType.FLOAT)],
                             [('mesh', DataType.GEOMETRY)],
                             []),
    'Join Strings': BuiltinNode('GeometryNodeStringJoin',
                                [('delimiter', DataType.STRING),
                                 ('strings', DataType.STRING)],
                                [('string', DataType.STRING)],
                                []),
    'Switch': BuiltinNode('GeometryNodeSwitch',
                          [('switch', DataType.BOOL), ('switch', DataType.BOOL), ('false', DataType.FLOAT), ('true', DataType.FLOAT), ('false', DataType.INT), ('true', DataType.INT), ('false', DataType.BOOL), ('true', DataType.BOOL), ('false', DataType.VEC3), ('true', DataType.VEC3), ('false', DataType.RGBA), ('true', DataType.RGBA), ('false', DataType.STRING), ('true', DataType.STRING), (
                              'false', DataType.GEOMETRY), ('true', DataType.GEOMETRY), ('false', DataType.OBJECT), ('true', DataType.OBJECT), ('false', DataType.COLLECTION), ('true', DataType.COLLECTION), ('false', DataType.TEXTURE), ('true', DataType.TEXTURE), ('false', DataType.MATERIAL), ('true', DataType.MATERIAL), ('false', DataType.IMAGE), ('true', DataType.IMAGE)],
                          [('output', DataType.FLOAT), ('output', DataType.INT), ('output', DataType.BOOL), ('output', DataType.VEC3), ('output', DataType.RGBA), ('output', DataType.STRING), ('output',
                                                                                                                                                                                                DataType.GEOMETRY), ('output', DataType.OBJECT), ('output', DataType.COLLECTION), ('output', DataType.TEXTURE), ('output', DataType.MATERIAL), ('output', DataType.IMAGE)],
                          [('input_type', ['FLOAT', 'INT', 'BOOLEAN', 'VECTOR', 'STRING', 'RGBA', 'OBJECT', 'IMAGE', 'GEOMETRY', 'COLLECTION', 'TEXTURE', 'MATERIAL'])]),
    'Star': BuiltinNode('GeometryNodeCurveStar',
                        [('points', DataType.INT), ('inner_radius', DataType.FLOAT),
                         ('outer_radius', DataType.FLOAT), ('twist', DataType.FLOAT)],
                        [('curve', DataType.GEOMETRY),
                         ('outer_points', DataType.BOOL)],
                        []),
    'Field at Index': BuiltinNode('GeometryNodeFieldAtIndex',
                                  [('index', DataType.INT), ('value', DataType.FLOAT), ('value', DataType.INT), (
                                      'value', DataType.VEC3), ('value', DataType.RGBA), ('value', DataType.BOOL)],
                                  [('value', DataType.FLOAT), ('value', DataType.INT), ('value',
                                                                                        DataType.VEC3), ('value', DataType.RGBA), ('value', DataType.BOOL)],
                                  [('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE']), ('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8'])]),
    'Viewer': BuiltinNode('GeometryNodeViewer',
                          [('geometry', DataType.GEOMETRY), ('value', DataType.FLOAT), ('value', DataType.VEC3), (
                              'value', DataType.RGBA), ('value', DataType.INT), ('value', DataType.BOOL)],
                          [],
                          [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8'])]),
    'String to Curves': BuiltinNode('GeometryNodeStringToCurves',
                                    [('string', DataType.STRING), ('size', DataType.FLOAT), ('character_spacing', DataType.FLOAT), ('word_spacing', DataType.FLOAT), (
                                        'line_spacing', DataType.FLOAT), ('text_box_width', DataType.FLOAT), ('text_box_height', DataType.FLOAT)],
                                    [('curve_instances', DataType.GEOMETRY), ('remainder', DataType.STRING),
                                     ('line', DataType.INT), ('pivot_point', DataType.VEC3)],
                                    [('overflow', ['OVERFLOW', 'SCALE_TO_FIT', 'TRUNCATE']), ('align_x', ['LEFT', 'CENTER', 'RIGHT', 'JUSTIFY', 'FLUSH']), ('align_y', ['TOP_BASELINE', 'TOP', 'MIDDLE', 'BOTTOM_BASELINE', 'BOTTOM']), ('pivot_mode', ['MIDPOINT', 'TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_CENTER', 'BOTTOM_RIGHT'])]),
    'Attribute Statistic': BuiltinNode('GeometryNodeAttributeStatistic',
                                       [('geometry', DataType.GEOMETRY), ('selection', DataType.BOOL),
                                        ('attribute', DataType.FLOAT), ('attribute', DataType.VEC3)],
                                       [('mean', DataType.FLOAT), ('median', DataType.FLOAT), ('sum', DataType.FLOAT), ('min', DataType.FLOAT), ('max', DataType.FLOAT), ('range', DataType.FLOAT), ('standard_deviation', DataType.FLOAT), ('variance', DataType.FLOAT),
                                        ('mean', DataType.VEC3), ('median', DataType.VEC3), ('sum', DataType.VEC3), ('min', DataType.VEC3), ('max', DataType.VEC3), ('range', DataType.VEC3), ('standard_deviation', DataType.VEC3), ('variance', DataType.VEC3)],
                                       [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8']), ('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE'])]),
    'Align Euler to Vector': BuiltinNode('FunctionNodeAlignEulerToVector',
                                         [('rotation', DataType.VEC3), ('factor',
                                                                        DataType.FLOAT), ('vector', DataType.VEC3)],
                                         [('rotation', DataType.VEC3)],
                                         [('axis', ['X', 'Y', 'Z']), ('pivot_axis', ['AUTO', 'X', 'Y', 'Z'])]),
    'Cube': BuiltinNode('GeometryNodeMeshCube',
                        [('size', DataType.VEC3), ('vertices_x', DataType.INT),
                         ('vertices_y', DataType.INT), ('vertices_z', DataType.INT)],
                        [('mesh', DataType.GEOMETRY)],
                        []),
    'Scale Instances': BuiltinNode('GeometryNodeScaleInstances',
                                   [('instances', DataType.GEOMETRY), ('selection', DataType.BOOL), (
                                       'scale', DataType.VEC3), ('center', DataType.VEC3), ('local_space', DataType.BOOL)],
                                   [('instances', DataType.GEOMETRY)],
                                   []),
    'Mesh Line': BuiltinNode('GeometryNodeMeshLine',
                             [('count', DataType.INT), ('resolution', DataType.FLOAT),
                              ('start_location', DataType.VEC3), ('offset', DataType.VEC3)],
                             [('mesh', DataType.GEOMETRY)],
                             [('mode', ['OFFSET', 'END_POINTS']), ('count_mode', ['TOTAL', 'RESOLUTION'])]),
    'Capture Attribute': BuiltinNode('GeometryNodeCaptureAttribute',
                                     [('geometry', DataType.GEOMETRY), ('value', DataType.VEC3), ('value', DataType.FLOAT), (
                                         'value', DataType.RGBA), ('value', DataType.BOOL), ('value', DataType.INT)],
                                     [('geometry', DataType.GEOMETRY), ('attribute', DataType.VEC3), ('attribute', DataType.FLOAT),
                                      ('attribute', DataType.RGBA), ('attribute', DataType.BOOL), ('attribute', DataType.INT)],
                                     [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8']), ('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE'])]),
    'Replace String': BuiltinNode('FunctionNodeReplaceString',
                                  [('string', DataType.STRING), ('find',
                                                                 DataType.STRING), ('replace', DataType.STRING)],
                                  [('string', DataType.STRING)],
                                  []),
    'Store Named Attribute': BuiltinNode('GeometryNodeStoreNamedAttribute',
                                         [('geometry', DataType.GEOMETRY), ('name', DataType.STRING), ('value', DataType.VEC3), (
                                             'value', DataType.FLOAT), ('value', DataType.RGBA), ('value', DataType.BOOL), ('value', DataType.INT)],
                                         [('geometry', DataType.GEOMETRY)],
                                         [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8']), ('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE'])]),
    'Bezier Segment': BuiltinNode('GeometryNodeCurvePrimitiveBezierSegment',
                                  [('resolution', DataType.INT), ('start', DataType.VEC3), ('start_handle',
                                                                                            DataType.VEC3), ('end_handle', DataType.VEC3), ('end', DataType.VEC3)],
                                  [('curve', DataType.GEOMETRY)],
                                  [('mode', ['POSITION', 'OFFSET'])]),
    'Random Value': BuiltinNode('FunctionNodeRandomValue',
                                [('min', DataType.VEC3), ('max', DataType.VEC3), ('min', DataType.FLOAT), ('max', DataType.FLOAT), ('min', DataType.INT), (
                                    'max', DataType.INT), ('probability', DataType.FLOAT), ('id', DataType.INT), ('seed', DataType.INT)],
                                [('value', DataType.VEC3), ('value', DataType.FLOAT),
                                 ('value', DataType.INT), ('value', DataType.BOOL)],
                                [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8'])]),
    'Instance on Points': BuiltinNode('GeometryNodeInstanceOnPoints',
                                      [('points', DataType.GEOMETRY), ('selection', DataType.BOOL), ('instance', DataType.GEOMETRY), (
                                          'pick_instance', DataType.BOOL), ('instance_index', DataType.INT), ('rotation', DataType.VEC3), ('scale', DataType.VEC3)],
                                      [('instances', DataType.GEOMETRY)],
                                      []),
    'Special Characters': BuiltinNode('FunctionNodeInputSpecialCharacters',
                                      [],
                                      [('line_break', DataType.STRING),
                                       ('tab', DataType.STRING)],
                                      []),
    'Compare': BuiltinNode('FunctionNodeCompare',
                           [('a', DataType.FLOAT), ('b', DataType.FLOAT), ('a', DataType.INT), ('b', DataType.INT), ('a', DataType.VEC3), ('b', DataType.VEC3), ('a', DataType.RGBA), (
                               'b', DataType.RGBA), ('a', DataType.STRING), ('b', DataType.STRING), ('c', DataType.FLOAT), ('angle', DataType.FLOAT), ('epsilon', DataType.FLOAT)],
                           [('result', DataType.BOOL)],
                           [('operation', ['LESS_THAN', 'LESS_EQUAL', 'GREATER_THAN', 'GREATER_EQUAL', 'EQUAL', 'NOT_EQUAL', 'BRIGHTER', 'DARKER']), ('data_type', ['FLOAT', 'INT', 'BOOLEAN', 'VECTOR', 'STRING', 'RGBA', 'OBJECT', 'IMAGE', 'GEOMETRY', 'COLLECTION', 'TEXTURE', 'MATERIAL']), ('mode', ['ELEMENT', 'LENGTH', 'AVERAGE', 'DOT_PRODUCT', 'DIRECTION'])]),
    'Float to Integer': BuiltinNode('FunctionNodeFloatToInt',
                                    [('float', DataType.FLOAT)],
                                    [('integer', DataType.INT)],
                                    [('rounding_mode', ['ROUND', 'FLOOR', 'CEILING', 'TRUNCATE'])]),
    'Domain Size': BuiltinNode('GeometryNodeAttributeDomainSize',
                               [('geometry', DataType.GEOMETRY)],
                               [('point_count', DataType.INT), ('edge_count', DataType.INT), ('face_count', DataType.INT),
                                ('face_corner_count', DataType.INT), ('spline_count', DataType.INT), ('instance_count', DataType.INT)],
                               [('component', ['MESH', 'POINTCLOUD', 'CURVE', 'INSTANCES'])]),
    'String Length': BuiltinNode('FunctionNodeStringLength',
                                 [('string', DataType.STRING)],
                                 [('length', DataType.INT)],
                                 []),
    'Ico Sphere': BuiltinNode('GeometryNodeMeshIcoSphere',
                              [('radius', DataType.FLOAT),
                               ('subdivisions', DataType.INT)],
                              [('mesh', DataType.GEOMETRY)],
                              []),
    'Accumulate Field': BuiltinNode('GeometryNodeAccumulateField',
                                    [('value', DataType.VEC3), ('value', DataType.FLOAT),
                                     ('value', DataType.INT), ('group_index', DataType.INT)],
                                    [('leading', DataType.VEC3), ('leading', DataType.FLOAT), ('leading', DataType.INT), ('trailing', DataType.VEC3), ('trailing',
                                                                                                                                                       DataType.FLOAT), ('trailing', DataType.INT), ('total', DataType.VEC3), ('total', DataType.FLOAT), ('total', DataType.INT)],
                                    [('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8']), ('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE'])]),
    'Quadratic Bezier': BuiltinNode('GeometryNodeCurveQuadraticBezier',
                                    [('resolution', DataType.INT), ('start', DataType.VEC3),
                                     ('middle', DataType.VEC3), ('end', DataType.VEC3)],
                                    [('curve', DataType.GEOMETRY)],
                                    []),
    'Cylinder': BuiltinNode('GeometryNodeMeshCylinder',
                            [('vertices', DataType.INT), ('side_segments', DataType.INT), ('fill_segments',
                                                                                           DataType.INT), ('radius', DataType.FLOAT), ('depth', DataType.FLOAT)],
                            [('mesh', DataType.GEOMETRY), ('top', DataType.BOOL),
                             ('side', DataType.BOOL), ('bottom', DataType.BOOL)],
                            [('fill_type', ['NONE', 'NGON', 'TRIANGLE_FAN'])]),
    'Spiral': BuiltinNode('GeometryNodeCurveSpiral',
                          [('resolution', DataType.INT), ('rotations', DataType.FLOAT), ('start_radius', DataType.FLOAT), (
                              'end_radius', DataType.FLOAT), ('height', DataType.FLOAT), ('reverse', DataType.BOOL)],
                          [('curve', DataType.GEOMETRY)],
                          []),
    'Transfer Attribute': BuiltinNode('GeometryNodeAttributeTransfer',
                                      [('source', DataType.GEOMETRY), ('attribute', DataType.VEC3), ('attribute', DataType.FLOAT), ('attribute', DataType.RGBA), (
                                          'attribute', DataType.BOOL), ('attribute', DataType.INT), ('source_position', DataType.VEC3), ('index', DataType.INT)],
                                      [('attribute', DataType.VEC3), ('attribute', DataType.FLOAT), ('attribute',
                                                                                                     DataType.RGBA), ('attribute', DataType.BOOL), ('attribute', DataType.INT)],
                                      [('mapping', ['NEAREST_FACE_INTERPOLATED', 'NEAREST', 'INDEX']), ('data_type', ['FLOAT', 'INT', 'FLOAT_VECTOR', 'FLOAT_COLOR', 'BYTE_COLOR', 'STRING', 'BOOLEAN', 'FLOAT2', 'INT8']), ('domain', ['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE'])]),
    'Quadrilateral': BuiltinNode('GeometryNodeCurvePrimitiveQuadrilateral',
                                 [('width', DataType.FLOAT), ('height', DataType.FLOAT), ('bottom_width', DataType.FLOAT), ('top_width', DataType.FLOAT), ('offset', DataType.FLOAT), ('bottom_height',
                                                                                                                                                                                       DataType.FLOAT), ('top_height', DataType.FLOAT), ('point_1', DataType.VEC3), ('point_2', DataType.VEC3), ('point_3', DataType.VEC3), ('point_4', DataType.VEC3)],
                                 [('curve', DataType.GEOMETRY)],
                                 [('mode', ['RECTANGLE', 'PARALLELOGRAM', 'TRAPEZOID', 'KITE', 'POINTS'])]),
    'Value to String': BuiltinNode('FunctionNodeValueToString',
                                   [('value', DataType.FLOAT),
                                    ('decimals', DataType.INT)],
                                   [('string', DataType.STRING)],
                                   []),
    'Translate Instances': BuiltinNode('GeometryNodeTranslateInstances',
                                       [('instances', DataType.GEOMETRY), ('selection', DataType.BOOL), (
                                           'translation', DataType.VEC3), ('local_space', DataType.BOOL)],
                                       [('instances', DataType.GEOMETRY)],
                                       []),
    'Image Texture': BuiltinNode('GeometryNodeImageTexture',
                                 [('image', DataType.IMAGE), ('vector',
                                                              DataType.VEC3), ('frame', DataType.INT)],
                                 [('color', DataType.RGBA),
                                  ('alpha', DataType.FLOAT)],
                                 [('interpolation', ['Linear', 'Closest', 'Cubic']), ('extension', ['REPEAT', 'EXTEND', 'CLIP'])]),
    'Mesh Circle': BuiltinNode('GeometryNodeMeshCircle',
                               [('vertices', DataType.INT),
                                ('radius', DataType.FLOAT)],
                               [('mesh', DataType.GEOMETRY)],
                               [('fill_type', ['NONE', 'NGON', 'TRIANGLE_FAN'])]),
}
