name: Code-Quality
on:
  pull_request:
    paths:
      - 'math_formula/*.py'
  push:
    paths:
      - 'math_formula/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code-Quality
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: 'pip'
    - run: pip install fake-bpy-module-latest
    - run: pip install "black<23" "pyright"
    - run: black --diff --check $(git ls-files 'math_formula/*.py')
    - run: pyright --level error --verbose math_formula/
