name: Code-Quality
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'math_formula/*.py'
  push:
    paths:
      - 'math_formula/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code-Quality
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.x
        cache: 'pip'
    - run: pip install -r ${{ github.workspace }}/.github/requirements.txt
    - run: black --diff --check $(git ls-files 'math_formula/*.py')
    - run: pyright --level error --verbose math_formula/
